name: flutter_manager
description: A useful command line tool for Flutter, which support flutter component management, built-in commands and custom command etc.（一个实用的Flutter命令行工具，支持 flutter 组件管理、内置命令和自定义命令等）
version: 1.0.2
homepage: https://github.com/GodJiong/flutter_manager
executables:
  manager:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #Parses raw command-line arguments into a set of options and values.
  args: ^2.3.1
  path: ^1.8.2
  yaml: ^3.1.1
  yaml_edit: ^2.1.0

dev_dependencies:
  test: ^1.21.4