name: power_command
description: A useful command line tool for Dart, which supports clean, pub get, pure etc.
version: 0.0.5
homepage: https://github.com/GodJiong/command
executables:
  power_command:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #Parses raw command-line arguments into a set of options and values.
  args: ^2.3.1
  path: ^1.8.2
  yaml: ^3.1.1
  yaml_writer: ^1.0.2

